Patch hotel events file

diff --git a/bin/patch_hotel_cors b/bin/patch_hotel_cors
--- a/bin/patch_hotel_cors
+++ b/bin/patch_hotel_cors
@@ -1,16 +1,17 @@
 #!/bin/sh
 
-#cat bin/patch_hotel_cors.patch
 hotel_bin=`which hotel`
 hotelSrcDir=`dirname $hotel_bin`
 hotelSrcDir=`dirname $hotelSrcDir`
 hotelSrcFile="$hotelSrcDir/lib/node_modules/hotel/lib/daemon/routers/api/events.js"
-echo "Patching $hotelSrcFile"
-patch $hotelSrcFile bin/patch_hotel_cors.patch
+echo "== Patching $hotelSrcFile =="
+patch $hotelSrcFile bin/0001-Patch-events.patch
 
-if [ $? -ne 0]; then
-  echo 'Patching failed. Please change the file manually according to the README.md'
+if [ $? -ne 0 ]; then
+  echo '== Patching failed. Reverting the changes. Please change the file manually according to the README.md =='
+  patch -R $hotelSrcFile bin/0001-Patch-events.patch
+  exit 1
 else
-  echo 'Patching successful. Restarting hotel...'
+  echo '== Patching successful. Restarting hotel... =='
   hotel stop && hotel start
 fi
